// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_SqRHdwOFdhzLDy5cbXKFpjdPgGuhHg',
    appId: '1:291139208558:web:3ce393b0c2f589fbafed7f',
    messagingSenderId: '291139208558',
    projectId: 'student-firebase-app-b68fd',
    authDomain: 'student-firebase-app-b68fd.firebaseapp.com',
    storageBucket: 'student-firebase-app-b68fd.firebasestorage.app',
    measurementId: 'G-HP1425X0DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMHi3_F9LRqqkHCU2wPsrFKMDcrwfAeLA',
    appId: '1:291139208558:android:4103cdb00632d5baafed7f',
    messagingSenderId: '291139208558',
    projectId: 'student-firebase-app-b68fd',
    storageBucket: 'student-firebase-app-b68fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDi8mRM1HjcyfX_8RfeQ4GHMdkhG99V2s',
    appId: '1:291139208558:ios:6bd582928a142796afed7f',
    messagingSenderId: '291139208558',
    projectId: 'student-firebase-app-b68fd',
    storageBucket: 'student-firebase-app-b68fd.firebasestorage.app',
    iosBundleId: 'com.example.sqliteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDi8mRM1HjcyfX_8RfeQ4GHMdkhG99V2s',
    appId: '1:291139208558:ios:6bd582928a142796afed7f',
    messagingSenderId: '291139208558',
    projectId: 'student-firebase-app-b68fd',
    storageBucket: 'student-firebase-app-b68fd.firebasestorage.app',
    iosBundleId: 'com.example.sqliteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_SqRHdwOFdhzLDy5cbXKFpjdPgGuhHg',
    appId: '1:291139208558:web:707da545013202cbafed7f',
    messagingSenderId: '291139208558',
    projectId: 'student-firebase-app-b68fd',
    authDomain: 'student-firebase-app-b68fd.firebaseapp.com',
    storageBucket: 'student-firebase-app-b68fd.firebasestorage.app',
    measurementId: 'G-5TNZX9RJ3M',
  );
}
